Add shared library compilation support
cursey/safetyhook pull request #71
Opened 2024-04-10 17:57 UTC by netadr

Add support for building `safetyhook` as a shared library by utilizing the CMake `BUILD_SHARED_LIBS` variable.

Note: In order to silence warnings regarding adding a dll-interface to STL classes, the `C4251` warning is silenced when compiling using MSVC.

Note: This change set also includes a fallback for calling `find_package(Zydis)` in order to resolve the `Zydis` dependency.

2024-05-15 05:58 UTC, cursey commented
Sorry for taking so long merging this PR in. It looks good to me but could you update it so its up to date with `main`? Thanks!

2025-02-10 13:40 UTC, aixxe requested changes

2025-02-10 13:40 UTC, aixxe commented on include/safetyhook/common.hpp
> +#define SATEFYHOOK_DLLIMPORT
```suggestion
#define SAFETYHOOK_DLLIMPORT
```

2025-02-20 08:10 UTC, cursey approved these changes

2025-02-20 08:11 UTC, merged